"""Handing a DAG run to goblin-watcher (gw) for an AI summary.

`i` on a run gathers everything airflow-watch can see about it — run metadata,
the DAG's own facts, every task instance, and their logs (`astro.
fetch_run_bundle`) — renders it into one report file, and launches
`gw scratch --prompt …` so a fresh agent session reads the report, summarizes
it, and then *stops*: the prompt explicitly forbids changes and says to wait
for instructions.

The prompt itself stays small — the run's identity plus the instructions — and
the bulk travels in the report file, because argv has a hard ceiling (~1 MB on
macOS) and a single task log can be twice that. Each log's contribution to the
report is bounded to its tail (`LOG_TAIL_CHARS`): failures announce themselves
at the end of a log, and an agent asked to read a 50 MB file summarizes nothing.

Like `tools/my_prs/gw.py` — whose stderr parsing this module reuses — the
dashboard shells out to the gw binary rather than importing goblin-watcher: gw
owns its config, state and tmux windowing, and its CLI is the stable seam
between the tools. The subprocess inherits stdin/stdout, so the app must be
suspended around `run_scratch` (outside tmux, gw execs `tmux attach`, which
needs the real terminal).
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from tools.my_prs.gw import error_line

from .astro import RunBundle
from .models import Dag, DagRun, Deployment

__all__ = [
    "LOG_TAIL_CHARS",
    "Investigation",
    "build_prompt",
    "prepare",
    "render_report",
    "run_scratch",
    "scratch_command",
    "scratch_name",
    "write_report",
]

# How much of each attempt's log the report keeps, from the end — the tail is
# where a failure explains itself. The cut is announced in place, so the reader
# (an agent) knows there was more and how much.
LOG_TAIL_CHARS = 16_000

# Where report files land: a stable, named directory under the system temp dir,
# so a session's reports are findable and the OS eventually reclaims them.
REPORT_DIR = "airflow-watch"


@dataclass(frozen=True, slots=True)
class Investigation:
    """One prepared hand-off: the report on disk and the `gw scratch` to run.

    Built entirely before anything is launched, so the app can log what is
    about to happen — and what it cost to gather — as one honest line.
    """

    name: str
    prompt: str
    path: Path
    tasks: int
    logs: int
    calls: int
    elapsed: float


def scratch_name(run: DagRun, now: datetime) -> str:
    """The scratch-space name: `af-<dag>-<timestamp>`.

    Named so `gw status` reads sensibly a week later; timestamped so two
    investigations of the same DAG never collide. Run ids are unusable here —
    `manual__2026-05-13T01:04:15+00:00` is not a directory name — so the DAG id
    is slugged and the moment of the hand-off stands in for the run.
    """
    return f"af-{_slug(run.dag_id)[:32]}-{now.strftime('%Y%m%d-%H%M%S')}"


def _slug(text: str) -> str:
    """Lowercase, dash-separated, nothing a filesystem or tmux will fight."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "run"


def log_tail(content: str, limit: int = LOG_TAIL_CHARS) -> tuple[str, bool]:
    """The last `limit` characters of a log, cut on a line boundary, plus
    whether anything was dropped."""
    if len(content) <= limit:
        return content, False
    tail = content[-limit:]
    cut = tail.find("\n")
    return (tail[cut + 1 :] if 0 <= cut < len(tail) - 1 else tail), True


def _stamp(value: datetime | None) -> str:
    return value.isoformat() if value is not None else "—"


def _seconds(value: float | None) -> str:
    return f"{value:.0f}s" if value is not None else "—"


def render_report(
    deployment: Deployment,
    run: DagRun,
    dag: Dag | None,
    bundle: RunBundle,
    now: datetime,
) -> str:
    """The whole story of one run, as markdown an agent will read.

    Ordered the way the investigation loop reads: identity, then the task
    instances in dependency order (the tree prefixes survive as plain text),
    then each attempt's log tail. Every omission — a skipped log, a truncated
    task list, a fetch that failed — is stated where it happened, because the
    reader cannot see what was left out of a file.
    """
    lines: list[str] = [
        f"# Airflow DAG run report: {run.dag_id} / {run.run_id}",
        "",
        f"Generated by airflow-watch at {now.isoformat()}.",
        "",
        "## Run",
        "",
        f"- deployment: {deployment.label} (Airflow {deployment.airflow_version})",
        f"- dag_id: {run.dag_id}",
        f"- run_id: {run.run_id}",
        f"- state: {run.state}",
        f"- run_type: {run.run_type or 'unknown'}",
        f"- logical_date: {_stamp(run.logical_date)}",
        f"- run_after: {_stamp(run.run_after)}",
        f"- started: {_stamp(run.start_date)}",
        f"- ended: {_stamp(run.end_date)}",
        f"- duration: {_seconds(run.duration)}",
        f"- note: {run.note or '—'}",
    ]
    if dag is not None:
        lines += [
            "",
            "## DAG",
            "",
            f"- schedule: {dag.schedule or '—'}",
            f"- owners: {', '.join(dag.owners) or '—'}",
            f"- tags: {', '.join(dag.tags) or '—'}",
            f"- paused: {dag.is_paused}",
            f"- stale (file gone from the bundle): {dag.is_stale}",
            f"- description: {dag.description or '—'}",
        ]

    held = len(bundle.rows)
    heading = f"## Task instances ({held}"
    if bundle.tasks_truncated:
        heading += f" of {bundle.tasks_total} — the task list was truncated"
    heading += ", in dependency order)"
    lines += ["", heading, ""]
    for row in bundle.rows:
        task = row.task
        marker = " · UNPLACED (cycle or missing upstream)" if row.unplaced else ""
        lines.append(
            f"- {row.label}: {task.state} · attempt {task.try_number} of "
            f"{task.max_tries or task.try_number} · {task.operator or 'unknown'} · "
            f"started {_stamp(task.start_date)} · duration "
            f"{_seconds(task.duration)} · pool {task.pool or '—'}{marker}"
        )

    lines += ["", "## Task logs", ""]
    if not bundle.logs:
        lines.append("No logs were fetched.")
    for attempt in bundle.logs:
        task = attempt.task
        lines.append(
            f"### {task.display_id} — attempt {attempt.try_number} of "
            f"{task.max_tries or task.try_number} ({task.state})"
        )
        lines.append("")
        if attempt.error is not None:
            lines.append(f"Log could not be fetched: {attempt.error}")
        elif attempt.log is None or not attempt.log.content.strip():
            lines.append("(empty log)")
        else:
            tail, cut = log_tail(attempt.log.content)
            if attempt.log.truncated:
                lines.append(
                    "[the fetch itself was truncated — this is not the whole log]"
                )
            if cut:
                lines.append(
                    f"[showing the last {LOG_TAIL_CHARS:,} of "
                    f"{len(attempt.log.content):,} characters]"
                )
            lines.append(tail.rstrip("\n"))
            lines.append(f"[end of log for {task.display_id} attempt {attempt.try_number}]")
        lines.append("")
    if bundle.skipped:
        lines += [
            f"{len(bundle.skipped)} attempt logs were not fetched "
            "(the per-investigation ceiling):",
            "",
        ]
        lines += [f"- {skipped}" for skipped in bundle.skipped]
        lines.append("")
    return "\n".join(lines)


def build_prompt(deployment: Deployment, run: DagRun, path: Path) -> str:
    """What the fresh gw session is seeded with: read the report, summarize,
    change nothing, wait. The 'change nothing' is load-bearing — the agent is
    being handed a report *about* production, in a scratch space with no
    project attached, and its job ends at understanding."""
    return (
        f"An Airflow DAG run needs investigating: {run.dag_id} / {run.run_id} "
        f"(state: {run.state}) on deployment {deployment.label} "
        f"(Airflow {deployment.airflow_version}).\n"
        "\n"
        "The full context airflow-watch gathered — run metadata, every task "
        "instance in dependency order, and their task logs — is in this file:\n"
        "\n"
        f"{path}\n"
        "\n"
        "Read it, then give a summary of the run: what ran, what failed or "
        "looks anomalous and why (quote the decisive log lines), and where you "
        "would look next. Do not make any changes of any kind — no files, no "
        "commands that mutate anything. After the summary, stop and wait for "
        "instructions."
    )


def scratch_command(name: str, prompt: str) -> list[str]:
    """The `gw scratch` invocation: a named scratch space, seeded with the
    prompt so the agent starts summarizing without being asked twice."""
    return ["gw", "scratch", name, "--prompt", prompt]


def write_report(text: str, name: str, directory: Path | None = None) -> Path:
    """Write the report where the agent can read it and return the path.

    A stable per-run filename in a named temp directory, not `mkstemp` noise:
    the path appears in the prompt and the activity log, and a human retracing
    the hand-off should recognize it.
    """
    parent = (directory or Path(tempfile.gettempdir())) / REPORT_DIR
    parent.mkdir(parents=True, exist_ok=True)
    path = parent / f"{name}.md"
    path.write_text(text)
    return path


def prepare(
    deployment: Deployment,
    run: DagRun,
    dag: Dag | None,
    bundle: RunBundle,
    now: datetime,
    directory: Path | None = None,
) -> Investigation:
    """Bundle → Investigation: render the report, write it, build the prompt.

    The one impure step is the file write; everything else is deterministic
    from its inputs, which is what the tests lean on.
    """
    name = scratch_name(run, now)
    path = write_report(render_report(deployment, run, dag, bundle, now), name, directory)
    return Investigation(
        name=name,
        prompt=build_prompt(deployment, run, path),
        path=path,
        tasks=len(bundle.tasks),
        logs=len(bundle.logs),
        calls=bundle.calls,
        elapsed=bundle.elapsed,
    )


def run_scratch(investigation: Investigation) -> tuple[str | None, str | None]:
    """Run `gw scratch` with the terminal's stdin/stdout (call this with the
    app suspended) and return `(message, error)` one-liners for the activity
    log. Blocks until gw exits — which, outside tmux, is when the user
    detaches from the agent's session."""
    if shutil.which("gw") is None:
        return None, "gw not found on PATH — is goblin-watcher installed?"
    proc = subprocess.run(
        scratch_command(investigation.name, investigation.prompt),
        stderr=subprocess.PIPE,
        text=True,
    )
    if proc.stderr:
        sys.stderr.write(proc.stderr)  # keep gw's own errors on the terminal too
    if proc.returncode != 0:
        return None, error_line(proc.stderr or "")
    return (
        f"gw: opened scratch {investigation.name} on {investigation.path.name} "
        f"({investigation.logs} logs).",
        None,
    )
