#!/usr/bin/env python3
"""Generate INDEX.md for an ADR corpus from frontmatter alone.

This is the deterministic half of the compacted read path, modeled on Kafka log
compaction: the ADR files are the append-only log, and INDEX.md is a projection
holding one row per record. Source files are never read for prose and never
rewritten. Delete INDEX.md and it comes back identical.

No model runs here, so the index cannot drift from what the frontmatter says.
Its model-authored sibling, CONSTRAINTS.md, is regenerated wholesale by the
adr-rpi skill and says so in its own header.

The output contains no generation timestamp on purpose: regenerating an
unchanged corpus produces byte-identical output, so `--check` is meaningful in
CI and a no-op regeneration makes no diff noise.

Usage:
    adr_index.py <corpus-dir>            # write <corpus-dir>/INDEX.md
    adr_index.py <corpus-dir> --stdout   # print instead of writing
    adr_index.py <corpus-dir> --check    # exit 1 if INDEX.md is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from adr_chain import ERROR, Adr, Corpus, load_corpus, validate  # noqa: E402

INDEX_NAME = "INDEX.md"
HEADER = (
    "<!-- GENERATED by the adr-rpi skill's scripts/adr_index.py from ADR frontmatter.\n"
    "     Do not edit: your changes are lost on the next regeneration.\n"
    "     Regenerate: python3 <skill>/scripts/adr_index.py <corpus-dir> -->"
)


def _cell(text: str) -> str:
    """Escape a value for a markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _link(corpus: Corpus, adr: Adr) -> str:
    return f"[{_cell(adr.id)}]({corpus.rel(adr)})"


def render_index(corpus: Corpus) -> str:
    active = [a for a in corpus.sorted_adrs() if a.active]
    superseded = [a for a in corpus.sorted_adrs() if not a.active]

    lines: list[str] = [HEADER, "", "# ADR index", ""]
    lines.append(f"{len(active)} active · {len(superseded)} superseded")
    lines.append("")

    if active:
        lines += [
            "## Active",
            "",
            "| ADR | Title | Status | Components | Ticket | Date |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for adr in active:
            lines.append(
                f"| {_link(corpus, adr)} | {_cell(adr.title)} | {adr.status} "
                f"| {_cell(', '.join(adr.components)) or '—'} | {_cell(adr.ticket or '—')} "
                f"| {adr.date} |"
            )
        lines.append("")

    if superseded:
        lines += [
            "## Superseded",
            "",
            "Not read during research. The ADR that replaced each of these carries",
            "forward whatever the chain concluded.",
            "",
            "| ADR | Title | Superseded by | Date |",
            "| --- | --- | --- | --- |",
        ]
        for adr in superseded:
            replacement = corpus.adrs.get(adr.superseded_by or "")
            target = _link(corpus, replacement) if replacement else _cell(adr.superseded_by or "—")
            lines.append(f"| {_link(corpus, adr)} | {_cell(adr.title)} | {target} | {adr.date} |")
        lines.append("")

    if not corpus.adrs:
        lines += ["No ADRs yet.", ""]

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("corpus", type=Path, help="ADR corpus directory, e.g. docs/adrs")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing INDEX.md")
    parser.add_argument("--check", action="store_true", help="exit 1 if INDEX.md is out of date")
    args = parser.parse_args(argv)

    corpus = load_corpus(args.corpus)
    rendered = render_index(corpus)

    # Structural errors are reported but do not block the index: a corpus that
    # will not project itself because one file is malformed is a corpus nobody
    # reads, and the errors are louder on stderr than in a missing file.
    errors = [p for p in validate(corpus) if p.level == ERROR]
    for problem in errors:
        print(problem.render(), file=sys.stderr)

    if args.stdout:
        print(rendered, end="")
        return 0

    target = args.corpus / INDEX_NAME
    if args.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != rendered:
            print(f"{target} is out of date; regenerate it", file=sys.stderr)
            return 1
        return 0

    target.write_text(rendered, encoding="utf-8")
    print(f"wrote {target} ({len(corpus.adrs)} ADRs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
